### ISSUE TITLE
Default bundle not showing

### ISSUE THREAD

**Issue by fx-nicolas** [essiembre/eclipse-rbe#25]
I'm using RBE to translate bundles for a dev team.
In certain project, the "default" bundle appears, in other project, it does not.§
I cannot figure out a pattern there. 
Any idea?
Thanks
FX

**Comment by Gummib-er** [comment]
I can confirm the issue. Using *Eclipse 4.4* and *RBE 1.0.4*, the "default" bundle often doesn't show up in RBE (although the RBE is started from the default bundle). Some resource bundles initially work, then they stop working at some time.
I am suspecting this issue might be related to the resource bundles being under version control using SVN. While I have no proof, the default bundle seems to go missing somewhen after the Eclipse projects are committed to SVN.

**Comment by fitoRiera** [comment]
I have same problem with a project under version control using git.

I also found the following behavior:
1-  Try to open the default bundle with RBE
2- The RBE opens but not show the default language
3- Ask RBE to create default language bundle
4- RBE creates a new file without extension for the default language bundle

**Comment by rheydenr** [comment]
Hi all, I've the same problem. Suddenly, without prenotification, the RBE doesn't show the default bundle tab. No idea what's wrong...

/Ralf.

**Comment by rsoucase** [comment]
I have a same problem Elclipse Luna 4.4, Dont show editor.

**Comment by Endeavourl** [comment]
Okay so with a bit of debugging we here realized what's wrong.

First, the workaround is to disable support for loading of resources from fragment (3rd checkbox from the top in settings), or close your plugin's fragments projects before opening resources.

Now, the error itself.
First, `ResourceFactory` uses `FragmentResourceFactory` if current project has fragments. It loads all available resources from all fragments and then calls `ResourceFactory` again to look for a factory to load host (current) project's resources, that is `StandardResourceFactory`.
`StandardResourceFactory `loads all the host's resources correctly, including the default resource for which it assigns the `Locale` value of `null`.
But then `FragmentResourceFactory` adds all the `SourceEditor`s created by `StandardResourceFactory` except those, which have `null` `Locale` thus discarding the default resource.

I'm not sure of implications of removing that `null` check, so i didn't try to make any changes.
Error line: https://github.com/essiembre/eclipse-rbe/blob/bf15767b27/eclipse-rbe-plugin/src/com/essiembre/eclipse/rbe/ui/editor/resources/FragmentResourceFactory.java#L161

**Comment by LZaruba** [comment]
Hi, 
I created a pull request which fixes this issue.
Can you please verify&accept this change or you can possibly give me an access to merge the change by myself.

Thank you

Lukas

**Comment by LZaruba** [comment]
Fixed in the latest release
