### ISSUE TITLE
Needs better how-to

### ISSUE THREAD

**Issue by easyaspi314** [essiembre/eclipse-rbe#32]

**Comment by easyaspi314** [comment]
In the README.md, there should be a better tutorial.

I, not very good at Eclipse (I code with it, run it, and that is it), it took me a while to get it right.

This is what I would suggest:

<h3>Step 1</h3>
Open Eclipse and go to Help > Install New Software…

<h3>Step 2</h3>
Hit the Add… button and enter the following:
Name: ResourceBundle Editor
Location: https://raw.githubusercontent.com/essiembre/eclipse-rbe/master/eclipse-rbe-update-site/site.xml
Check the item that says "Resource Bundle Editor", hit Next, and follow the steps. 

Eclipse may ask you if you want to install the unsigned plugin, just install it anyway.

Restart Eclipse at the prompt.
 
<h3>Step 3</h3>
To create a new ResourceBundle, hit Ctrl/Cmd+N and under the folder "ResourceBundle", double-click "ResourceBundle", and follow the wizard.

<h3>Step 4</h3>
If you do not see the editor and instead see a plain text editor with this,

`#Generated by ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)`

Right-click the editor and go to Open With > ResourceBundle Editor.

Source:
==
```markdown
<h3>Step 1</h3>
Open Eclipse and go to Help > Install New Software…

<h3>Step 2</h3>
Hit the Add… button and enter the following:
Name: ResourceBundle Editor
Location: https://raw.githubusercontent.com/essiembre/eclipse-rbe/master/eclipse-rbe-update-site/site.xml
Check the item that says "Resource Bundle Editor", hit Next, and follow the steps. 

Eclipse may ask you if you want to install the unsigned plugin, just install it anyway.

Restart Eclipse at the prompt.
 
<h3>Step 3</h3>
To create a new ResourceBundle, hit Ctrl/Cmd+N and under the folder "ResourceBundle", double-click "ResourceBundle", and follow the wizard.

<h3>Step 4</h3>
If you do not see the editor and instead see a plain text editor with this,

`#Generated by ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)`

Right-click the editor and go to Open With > ResourceBundle Editor.
```

**Comment by cserge** [comment]
Thank you, thank you, thank you. Exactly what I needed.

**Comment by k0ner** [comment]
Right now you can use *drag to install* button so I'm closing this issue.
