### ISSUE TITLE
Looking for Collaborators

### ISSUE THREAD

**Issue by essiembre** [essiembre/eclipse-rbe#35]
Hello, due to lack of available time to commit on this project, I am looking for collaborators to help out.  Anybody interested developers can respond to this issue.   Any of you who submitted pull requests interested? @jrodalo, @Gummib-er, or @sergm? Others?

**Comment by Gummib-er** [comment]
I would be happy to contribute to this project. Jörg

**Comment by essiembre** [comment]
@Gummib-er, can you please send me an email (look at my github profile to get mine).  I will grant you access and share basic info.

**Comment by essiembre** [comment]
Good news: @k0ner and @LZaruba accepted to join as collaborators!  We should see more traction on this project now.  I am closing this issue, but people willing to collaborate can still reach me.

Thanks @k0ner and @LZaruba!
