### ISSUE TITLE
Option to ignore key case

### ISSUE THREAD

**Issue by rusak47** [essiembre/eclipse-rbe#78]
It would be useful to add option to ignore key case in RBE preferences. It will help to avoid key duplicates, when file is managed by multiple users.
I.e. historically keys where added in camelCase, but recently was decided to use lowercase.
Now RBE threats translationkey and translationKey as different records.

**Comment by k0ner** [comment]
@diabolusss this would introduce too much of a burden. It is user's responsibility to create a standard to follow.
